var = {
    0: 'Luck is on your side. You will be very lucky soon, do not miss this moment! ',
    1: 'It is time to get out of your comfort zone! Do not be afraid of the new. ',
    2: 'Good news will be knocking on the door soon.',
    3: 'Trust in others, but do not make a mistake yourself!',
    4: 'Happiness is just around the corner.',
    5: 'Do not miss your chance.',
    6: 'Sometimes you just have to go with the flow.',
    7: 'Someone is gossiping about you behind your back.',
    8: 'Slow down! Remember what it is like to live and enjoy life. ',
    9: 'A wonderful life awaits you.',
    10: 'Stop dreaming, it is time to achieve goals!',
    11: 'Watch your words. Remember, lies always come up at the most inopportune moment. ',
    12: 'An important meeting awaits you, very soon.',
    13: 'You have got a white streak in your life, stay on course.',
    14: 'Do not throw words into the wind.',
    15: 'Pay attention to work, you will get a promotion.',
    16: 'Forget about the past and stop digging into it. Just look ahead! ',
    17: 'You are the darling of fate.',
    18: 'Now is the best time to meet new people.',
    19: 'You will have a very successful year.',
    20: 'Do not let your luck go.',
    21: 'Live today, think about tomorrow.',
    22: 'Listen to your intuition, she speaks.',
    23: 'Speak carefully, every word matters.',
    24: 'Trials await you, show restraint.',
    25: 'Night is a magical time for you.',
    26: 'Be positive and share it with others.',
    27: 'You urgently need a rest.',
    28: 'Stop complaining about life - it is not as bad as it seems.',
    29: 'Do not give up! Everything will work out, there is still a little left. ',
    30: 'Life will give you a pleasant surprise.',
    31: 'Time to Finish Old Things.',
    32: 'Your dream will soon come true.',
    33: 'Think before you speak.',
    34: 'More self-confidence.',
    35: 'Good luck by your side.',
    36: 'You will get the chance to meet new people. Do not miss it. ',
    37: 'Love yourself - and those around you will love you.',
    38: 'Something big is about to happen.',
    39: 'There is a long and easy life ahead.',
    40: 'Everything is much better than you think.',
    41: 'Keep your mouth shut, sometimes it is better to remain silent.',
    42: 'You are waiting for cardinal changes in your life.',
    43: 'Your life is sweet as raspberries.',
    44: 'Do not rush to change jobs.',
    45: 'Show respect for others and they will respect you too.',
    46: 'Do not stop - you are close to the goal.',
    47: 'Do what you like.',
    48: 'Weigh your actions.',
    49: 'Fortune favors you.',
    50: 'Do an act that is not in your nature. It will be good. ',
    51: 'Take care of your friends.',
    52: 'It is time to get rid of all unnecessary things.',
    53: 'Do not be fooled.',
    54: 'Risk is a noble cause.',
    55: 'Catch your luck by the tail.',
    56: 'Do not be afraid of new things, do things.',
    57: 'Wait for good news.',
    58: 'You are the master of your life. Count on yourself only. ',
    59: 'Your happiness is just around the corner.',
    60: 'Take the chance.',
    61: 'Just go with the flow.',
    62: 'Someone is discussing you behind your back.',
    63: 'Take some time for yourself, you need it.',
    64: 'Life is beautiful.',
    65: 'Stop dreaming - do it.',
    66: 'All secrets are revealed.',
    67: 'Soon you will have a fateful meeting.',
    68: 'A white streak awaits you in life.',
    69: 'Words are important, do not litter them.',
    70: 'Do not Miss Your Chance.',
    71: 'Sometimes you just have to go with the flow.',
    72: 'Someone is gossiping about you behind your back.',
    73: 'Listen to your intuition, she speaks.',
    74: 'Speak carefully, every word counts.',
    75: 'Trials await you, show restraint.',
    76: 'Good news will knock on the door soon.',
    77: 'Trust in others, but do not make a mistake yourself!',
    78: 'Show respect for others and they will respect you too.',
    79: 'Do not stop - you are close to your goal.',
    80: 'Live today, think about tomorrow.',
    81: 'Listen to your intuition, she speaks.',
    82: 'Speak carefully, every word counts.',
    83: 'Listen to your heart.',
    84: 'You deserve it.',
    85: 'Your life is only your business.',
    86: 'Life is great.',
    87: 'Be careful with your health.',
    88: 'Tests await you, show restraint.',
    89: 'The Night Is A Magic Time For You.',
    90: 'Be positive and share it with others.',
    91: 'Do not miss your chance.',
    92: 'We need a little rest.',
    93: 'Take care of yourself.',
    94: 'Yes, that is what you need.',
    95: 'Listen to your intuition, she speaks.',
    96: 'Speak carefully, every word counts.',
    97: 'Life is beautiful.',
    98: 'Stop Dreaming - Act.',
    99: 'All secrets are revealed.'
}
